# DF-CONST-AUTO-EXPANSION Engine [CRUX-MK]
"""
Engine fuer Daily-Cadence Konst-Auto-Expansion.

Detektiert NEUE Konst-Klassen in klassen_variant_tables.py + generiert pro Konst:
- 5 Tier-Vertraege (Tier-1 bis Tier-5) als YAML-Skelett
- 50 Klausel-Begruendungen als MD-Skelett

Architektur:
- KonstDetector: Liest klassen_variant_tables.py, extrahiert Konst-IDs
- ExistingScanner: Findet welche Konsts bereits 5+50-Skelett haben
- TierTemplateEngine: Generiert YAML-Tier-Skelette
- KlauselTemplateEngine: Generiert MD-Klausel-Skelette
- AuditLogger + K16Mutex + PreAction (analog DF-A/B)
"""
from __future__ import annotations

import ast
import json
import os
import re
import time
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ============================================================
# Konst-Detector
# ============================================================

class KonstDetector:
    """Detektiert Konst-IDs in klassen_variant_tables.py."""

    KONST_PATTERN = re.compile(r"['\"]([Kk]\d+|KONST_\d+)['\"]")

    @staticmethod
    def detect(python_path: Path) -> list[str]:
        """Returns sorted unique Liste aller Konst-IDs in der Datei."""
        if not python_path.exists():
            return []
        try:
            text = python_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            return []
        matches = KonstDetector.KONST_PATTERN.findall(text)
        # Normalize: K01 == K1
        normed = set()
        for m in matches:
            if m.upper().startswith("K") and not m.startswith("KONST_"):
                # K01, K1 -> uniformize: K01 (zero-padded)
                num_part = m[1:]
                if num_part.isdigit():
                    normed.add(f"K{int(num_part):02d}")
                else:
                    normed.add(m.upper())
            else:
                normed.add(m.upper())
        return sorted(normed)


# ============================================================
# Existing-Scanner
# ============================================================

class ExistingScanner:
    """Findet welche Konsts schon 5-Tier + 50-Klausel-Skelett haben."""

    def __init__(self, vertrags_root: Path, klauseln_root: Path,
                 tiers_per_konst: int = 5, klauseln_per_konst: int = 50):
        self.vertrags_root = vertrags_root
        self.klauseln_root = klauseln_root
        self.tiers_per_konst = tiers_per_konst
        self.klauseln_per_konst = klauseln_per_konst

    def is_complete(self, konst_id: str) -> dict[str, Any]:
        """Returns {complete: bool, tiers_found: int, klauseln_found: int}."""
        tiers_dir = self.vertrags_root / konst_id
        klauseln_dir = self.klauseln_root / konst_id
        tiers_count = 0
        klauseln_count = 0
        if tiers_dir.exists():
            tiers_count = len([f for f in tiers_dir.glob("tier-*.yaml") if f.is_file()])
        if klauseln_dir.exists():
            klauseln_count = len([f for f in klauseln_dir.glob("klausel-*.md") if f.is_file()])
        complete = (tiers_count >= self.tiers_per_konst
                    and klauseln_count >= self.klauseln_per_konst)
        return {
            "konst_id": konst_id,
            "complete": complete,
            "tiers_found": tiers_count,
            "klauseln_found": klauseln_count,
        }


# ============================================================
# TierTemplateEngine
# ============================================================

class TierTemplateEngine:
    """Generiert 5-Tier-YAML-Skelette pro Konst."""

    @staticmethod
    def render(konst_id: str, tier: int) -> str:
        """Skelett-YAML fuer eine Konst-Tier-Kombination."""
        return (
            f"# Auto-generated by DF-CONST-AUTO-EXPANSION [CRUX-MK]\n"
            f"konst_id: {konst_id}\n"
            f"tier: Tier-{tier}\n"
            f"status: SKELETON\n"
            f"version: 0.1.0\n"
            f"created_iso: {datetime.now(tz=timezone.utc).isoformat()}\n"
            f"name: '{konst_id} Tier-{tier} (skeleton)'\n"
            f"variant_summary: |\n"
            f"  TODO: Inhalt fuer {konst_id} Tier-{tier} ergaenzen.\n"
            f"klauseln:\n"
            f"  - klausel_id: TODO\n"
            f"    text: TODO\n"
            f"acceptance_criteria:\n"
            f"  K11_cascade_isolation: TBD\n"
            f"  K12_provenance: auto-generated\n"
            f"  K13_external_anchor: github_filesystem\n"
            f"  K14_override_complexity: single_command\n"
            f"  K15_entropy_added_loc_estimate: 0\n"
            f"  K16_concurrent_spawn_protection: both\n"
        )

    def generate_for_konst(self, konst_id: str, tiers_dir: Path,
                          tiers_count: int = 5,
                          overwrite: bool = False) -> list[Path]:
        """Erstellt tier-1.yaml ... tier-N.yaml."""
        tiers_dir.mkdir(parents=True, exist_ok=True)
        created: list[Path] = []
        for tier in range(1, tiers_count + 1):
            path = tiers_dir / f"tier-{tier}.yaml"
            if path.exists() and not overwrite:
                continue
            path.write_text(TierTemplateEngine.render(konst_id, tier), encoding="utf-8")
            created.append(path)
        return created


# ============================================================
# KlauselTemplateEngine
# ============================================================

class KlauselTemplateEngine:
    """Generiert 50-Klausel-MD-Skelette pro Konst."""

    @staticmethod
    def render(konst_id: str, klausel_num: int) -> str:
        kid = f"{konst_id}-K{klausel_num:03d}"
        return (
            f"# Klausel-Begruendung {kid} [CRUX-MK]\n\n"
            f"**Auto-generated by DF-CONST-AUTO-EXPANSION**\n"
            f"**Status:** SKELETON\n"
            f"**Created:** {datetime.now(tz=timezone.utc).isoformat()}\n\n"
            f"## Klausel-Text\n\n"
            f"TODO: Klausel-Text fuer {kid}.\n\n"
            f"## Begruendung\n\n"
            f"TODO: Rechtliche / wirtschaftliche / vertragliche Begruendung.\n\n"
            f"## Cross-Reference\n\n"
            f"- Konst: {konst_id}\n"
            f"- Klausel-Nummer: {klausel_num}\n\n"
            f"## CRUX-Bindung\n\n"
            f"- K_0 Schutz: TBD\n"
            f"- Q_0 Schutz: TBD\n"
            f"- W_0 Optimierung: TBD\n\n"
            f"[CRUX-MK]\n"
        )

    def generate_for_konst(self, konst_id: str, klauseln_dir: Path,
                           klauseln_count: int = 50,
                           overwrite: bool = False) -> list[Path]:
        klauseln_dir.mkdir(parents=True, exist_ok=True)
        created: list[Path] = []
        for n in range(1, klauseln_count + 1):
            path = klauseln_dir / f"klausel-{n:03d}.md"
            if path.exists() and not overwrite:
                continue
            path.write_text(KlauselTemplateEngine.render(konst_id, n), encoding="utf-8")
            created.append(path)
        return created


# ============================================================
# Logger + Mutex (Pattern-Reuse)
# ============================================================

class AuditLogger:
    def __init__(self, log_path: Path):
        self.log_path = log_path
        self.log_path.parent.mkdir(parents=True, exist_ok=True)

    def log(self, event: dict[str, Any]) -> None:
        event["ts"] = event.get("ts", datetime.now(tz=timezone.utc).isoformat())
        with self.log_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(event, ensure_ascii=False) + "\n")


class K16Mutex:
    def __init__(self, lock_dir: Path, stale_age_h: int = 3):
        self.lock_dir = lock_dir
        self.stale_age_h = stale_age_h

    def acquire(self) -> bool:
        if self.lock_dir.exists():
            stat = self.lock_dir.stat()
            age_s = time.time() - stat.st_mtime
            if age_s > self.stale_age_h * 3600:
                try:
                    pid_file = self.lock_dir / "pid"
                    if pid_file.exists():
                        pid_file.unlink()
                    self.lock_dir.rmdir()
                except OSError:
                    pass
        try:
            self.lock_dir.mkdir(parents=False, exist_ok=False)
            (self.lock_dir / "pid").write_text(str(os.getpid()))
            return True
        except FileExistsError:
            return False

    def release(self) -> None:
        try:
            pid_file = self.lock_dir / "pid"
            if pid_file.exists():
                pid_file.unlink()
            if self.lock_dir.exists():
                self.lock_dir.rmdir()
        except OSError:
            pass


@dataclass
class PreActionCheck:
    env_tag: str
    mount_point: str
    backup_status: str
    blast_radius: str
    reversibility_class: str
    timestamp_iso: str

    def passes(self) -> bool:
        if self.env_tag not in ("dev", "staging", "prod"):
            return False
        if self.reversibility_class not in ("state_only", "side_effect"):
            return False
        return True


# ============================================================
# Main-Run
# ============================================================

@dataclass
class ExpansionRunResult:
    run_id: str
    started_iso: str
    finished_iso: str
    konsts_detected: list[str]
    konsts_expanded: list[str]
    tier_files_created: int
    klausel_files_created: int
    skipped_due_to_stop_flag: bool

    def summary(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "konsts_detected_count": len(self.konsts_detected),
            "konsts_expanded_count": len(self.konsts_expanded),
            "tier_files_created": self.tier_files_created,
            "klausel_files_created": self.klausel_files_created,
            "skipped": self.skipped_due_to_stop_flag,
        }


def run_expansion(
    base_dir: Path,
    config: dict,
    stop_flag: Path | None = None,
) -> ExpansionRunResult:
    """Hauptlauf."""
    run_id = f"expand-{datetime.now(tz=timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
    started = datetime.now(tz=timezone.utc).isoformat()

    mutex = K16Mutex(Path(config["k16_concurrent_spawn_mutex"]["lock_dir"]))
    if not mutex.acquire():
        raise RuntimeError("K16-VETO: Lock held")

    try:
        if stop_flag and stop_flag.exists():
            return ExpansionRunResult(
                run_id=run_id,
                started_iso=started,
                finished_iso=datetime.now(tz=timezone.utc).isoformat(),
                konsts_detected=[],
                konsts_expanded=[],
                tier_files_created=0,
                klausel_files_created=0,
                skipped_due_to_stop_flag=True,
            )

        # K13-PAV
        pac = PreActionCheck(
            env_tag=os.environ.get("DF_ENV_TAG", "prod"),
            mount_point=str(base_dir),
            backup_status="git_mirror_ok" if base_dir.exists() else "missing",
            blast_radius="write_skeleton_yamls_plus_audit_log",
            reversibility_class="side_effect",
            timestamp_iso=datetime.now(tz=timezone.utc).isoformat(),
        )
        if not pac.passes():
            raise RuntimeError(f"K13-PAV-FAIL: {pac}")

        # Konst-Detection
        python_path = base_dir / config["paths"]["python_table_path"]
        konsts = KonstDetector.detect(python_path)

        # Existing-Scan + Expand
        scanner = ExistingScanner(
            base_dir / config["paths"]["vertrags_root"],
            base_dir / config["paths"]["klauseln_root"],
            tiers_per_konst=config["generation"]["tiers_per_konst"],
            klauseln_per_konst=config["generation"]["klauseln_per_konst"],
        )
        tier_engine = TierTemplateEngine()
        klausel_engine = KlauselTemplateEngine()
        expanded: list[str] = []
        tier_total = 0
        klausel_total = 0
        for konst in konsts:
            status = scanner.is_complete(konst)
            if status["complete"]:
                continue
            tiers_dir = base_dir / config["paths"]["vertrags_root"] / konst
            klauseln_dir = base_dir / config["paths"]["klauseln_root"] / konst
            new_tiers = tier_engine.generate_for_konst(
                konst, tiers_dir,
                tiers_count=config["generation"]["tiers_per_konst"],
                overwrite=config["generation"]["overwrite_existing"],
            )
            new_klauseln = klausel_engine.generate_for_konst(
                konst, klauseln_dir,
                klauseln_count=config["generation"]["klauseln_per_konst"],
                overwrite=config["generation"]["overwrite_existing"],
            )
            tier_total += len(new_tiers)
            klausel_total += len(new_klauseln)
            if new_tiers or new_klauseln:
                expanded.append(konst)

        # Audit-Log
        logger = AuditLogger(base_dir / config["paths"]["audit_log"])
        logger.log({
            "run_id": run_id,
            "konsts_detected": len(konsts),
            "konsts_expanded": len(expanded),
            "tier_files": tier_total,
            "klausel_files": klausel_total,
        })

        return ExpansionRunResult(
            run_id=run_id,
            started_iso=started,
            finished_iso=datetime.now(tz=timezone.utc).isoformat(),
            konsts_detected=konsts,
            konsts_expanded=expanded,
            tier_files_created=tier_total,
            klausel_files_created=klausel_total,
            skipped_due_to_stop_flag=False,
        )
    finally:
        mutex.release()


if __name__ == "__main__":
    import yaml  # type: ignore[import-untyped]
    config_path = Path(__file__).parent.parent / "config.yaml"
    config = yaml.safe_load(config_path.read_text())
    base_dir = Path(os.environ.get("DF_BASE_DIR", "/tmp/df-const-auto-expansion-test"))
    result = run_expansion(base_dir, config)
    print(json.dumps(result.summary(), indent=2))
